version: '3'
volumes:
    mysql-log:
        driver: local
    mysql-data:
        driver: local
services:
  #
  # mysql
  #
  db:
    build: ./mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '53307:3306'
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql-log:/var/log/mysql
      - mysql-data:/var/lib/mysql
  #
  # web
  #
  web:
    build:
      context: ..
      dockerfile: python/Dockerfile
    image: python:3.8
    restart: always
    user: "${USERID:?required USERID}:${GROUPID:?required GROUPID}"
    environment:
      DJANGO_SETTINGS_MODULE: app.settings.dev
    command: sh -c "python manage.py runserver 0.0.0.0:8000 > /log/django.log 2>&1"
    ports:
      - '58000:8000'
    volumes:
      - .:/code
      - ./log:/log
    depends_on:
        - db
